url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Team Inspiration" # the name of your site, e.g. ACME Corp.
timezone: America/Los_Angeles
    
# Build settings
markdown: kramdown
permalink: pretty
future: true

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
    
include:
  - _pages

sass:
  sass_dir: assets/css

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md


